const StudentsData = [
  {
    id: 1,
    name: "Shirley A. Lape",
    department: "Electrical Department",
    IdNumber: "ETS 0001/13",
    Gender: "Female",
    Role: "Student",
    PhoneNumber: "+251000000000",
  },
  {
    id: 2,
    name: "Ryan Carroll",
    department: "Chemical Department",
    IdNumber: "ETS 0002/13",
    Gender: "Male",
    Role: "Representative",
    PhoneNumber: "+251000000001",
    SubDepart: "Applied Science",
  },
  {
    id: 3,
    name: "Mason Nash",
    department: "Software Department",
    IdNumber: "ETS 0003/13",
    Gender: "Male",
    Role: "Student Union",
    PhoneNumber: "+251000000002",
    SubDepart: "Applied Science",
  },
  {
    id: 4,
    name: "Shirley A. Lape",
    department: "Electrical Department",
    IdNumber: "ETS 0001/13",
    Gender: "Female",
    Role: "Student",
    PhoneNumber: "+251000000000",
    SubDepart: "Applied Science",
  },
  {
    id: 5,
    name: "Shirley A. Lape",
    department: "Electrical Department",
    IdNumber: "ETS 0001/13",
    Gender: "Female",
    Role: "Student",
    PhoneNumber: "+251000000000",
    SubDepart: "Applied Science",
  },
  {
    id: 6,
    name: "Shirley A. Lape",
    department: "Electrical Department",
    IdNumber: "ETS 0001/13",
    Gender: "Female",
    Role: "Student",
    PhoneNumber: "+251000000000",
    SubDepart: "Applied Science",
  },
  {
    id: 7,
    name: "Shirley A. Lape",
    department: "Electrical Department",
    IdNumber: "ETS 0001/13",
    Gender: "Female",
    Role: "Student",
    PhoneNumber: "+251000000000",
  },
  {
    id: 8,
    name: "Shirley A. Lape",
    department: "Electrical Department",
    IdNumber: "ETS 0001/13",
    Gender: "Female",
    Role: "Student",
    PhoneNumber: "+251000000000",
  },
  {
    id: 9,
    name: "Shirley A. Lape",
    department: "Electrical Department",
    IdNumber: "ETS 0001/13",
    Gender: "Female",
    Role: "Student",
    PhoneNumber: "+251000000000",
  },
  {
    id: 10,
    name: "Shirley A. Lape",
    department: "Electrical Department",
    IdNumber: "ETS 0001/13",
    Gender: "Female",
    Role: "Student",
    PhoneNumber: "+251000000000",
  },
  {
    id: 11,
    name: "Shirley A. Lape",
    department: "Electrical Department",
    IdNumber: "ETS 0001/13",
    Gender: "Female",
    Role: "Student",
    PhoneNumber: "+251000000000",
  },
  {
    id: 12,
    name: "Shirley A. Lape",
    department: "Electrical Department",
    IdNumber: "ETS 0001/13",
    Gender: "Female",
    Role: "Student",
    PhoneNumber: "+251000000000",
  },
  {
    id: 13,
    name: "Shirley A. Lape",
    department: "Electrical Department",
    IdNumber: "ETS 0001/13",
    Gender: "Female",
    Role: "Student",
    PhoneNumber: "+251000000000",
  },
];

export default StudentsData;
